'use strict';window.DOMHandler=class{constructor(d,g){this._iRuntime=d;this._componentId=g;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(d,g,k,m){this._iRuntime.PostToRuntimeComponent(this._componentId,d,g,k,m)}PostToRuntimeAsync(d,g,k,m){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,d,g,k,m)}_PostToRuntimeMaybeSync(d,g,k){this._iRuntime.UsesWorker()?this.PostToRuntime(d,g,k):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:d,dispatchOpts:k||null,data:g,responseId:null})}AddRuntimeMessageHandler(d,g){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,d,g)}AddRuntimeMessageHandlers(d){for(const [g,k]of d)this.AddRuntimeMessageHandler(g,k)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(d,g){this._callback=d;this._interval=g;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(d){this._canRunImmediate=!!d}Call(){if(-1===this._timerId){var d=Date.now(),g=d-this._lastCallTime,k=this._interval;g>=k&&this._canRunImmediate?(this._lastCallTime=d,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(k-g,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(d,g){super(d,g);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",k=>this._OnCreate(k)],["destroy",k=>this._OnDestroy(k)],["set-visible",k=>this._OnSetVisible(k)],["update-position",k=>this._OnUpdatePosition(k)],["update-state",k=>this._OnUpdateState(k)],["focus",k=>this._OnSetFocus(k)],["set-css-style",k=>this._OnSetCssStyle(k)],["set-attribute",k=>this._OnSetAttribute(k)],["remove-attribute",
k=>this._OnRemoveAttribute(k)]]);this.AddDOMElementMessageHandler("get-element",k=>k)}SetAutoAttach(d){this._autoAttach=!!d}AddDOMElementMessageHandler(d,g){this.AddRuntimeMessageHandler(d,k=>{const m=this._elementMap.get(k.elementId);return g(m,k)})}_OnCreate(d){const g=d.elementId,k=this.CreateElement(g,d);this._elementMap.set(g,k);d.isVisible||(k.style.display="none");d=this._GetFocusElement(k);d.addEventListener("focus",m=>this._OnFocus(g));d.addEventListener("blur",m=>this._OnBlur(g));this._autoAttach&&
document.body.appendChild(k)}CreateElement(d,g){throw Error("required override");}DestroyElement(d){}_OnDestroy(d){d=d.elementId;const g=this._elementMap.get(d);this.DestroyElement(g);this._autoAttach&&g.parentElement.removeChild(g);this._elementMap.delete(d)}PostToRuntimeElement(d,g,k){k||(k={});k.elementId=g;this.PostToRuntime(d,k)}_PostToRuntimeElementMaybeSync(d,g,k){k||(k={});k.elementId=g;this._PostToRuntimeMaybeSync(d,k)}_OnSetVisible(d){this._autoAttach&&(this._elementMap.get(d.elementId).style.display=
d.isVisible?"":"none")}_OnUpdatePosition(d){if(this._autoAttach){var g=this._elementMap.get(d.elementId);g.style.left=d.left+"px";g.style.top=d.top+"px";g.style.width=d.width+"px";g.style.height=d.height+"px";d=d.fontSize;null!==d&&(g.style.fontSize=d+"em")}}_OnUpdateState(d){const g=this._elementMap.get(d.elementId);this.UpdateState(g,d)}UpdateState(d,g){throw Error("required override");}_GetFocusElement(d){return d}_OnFocus(d){this.PostToRuntimeElement("elem-focused",d)}_OnBlur(d){this.PostToRuntimeElement("elem-blurred",
d)}_OnSetFocus(d){const g=this._GetFocusElement(this._elementMap.get(d.elementId));d.focus?g.focus():g.blur()}_OnSetCssStyle(d){this._elementMap.get(d.elementId).style[d.prop]=d.val}_OnSetAttribute(d){this._elementMap.get(d.elementId).setAttribute(d.name,d.val)}_OnRemoveAttribute(d){this._elementMap.get(d.elementId).removeAttribute(d.name)}GetElementById(d){return this._elementMap.get(d)}};"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function g(p){if(p.isStringSrc){const c=document.createElement("script");c.async=!1;c.textContent=p.str;document.head.appendChild(c)}else return new Promise((c,e)=>{const a=document.createElement("script");a.onload=c;a.onerror=e;a.async=!1;a.src=p;document.head.appendChild(a)})}let k=new Audio;const m={"audio/webm; codecs=opus":!!k.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!k.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!k.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!k.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!k.canPlayType("audio/mp4"),"audio/mpeg":!!k.canPlayType("audio/mpeg")};k=null;async function n(p){p=await z(p);return(new TextDecoder("utf-8")).decode(p)}function z(p){return new Promise((c,e)=>{const a=new FileReader;a.onload=b=>c(b.target.result);a.onerror=b=>e(b);a.readAsArrayBuffer(p)})}const v=[];let u=0;window.RealFile=window.File;const t=
[],w=new Map,x=new Map;let A=0;const B=[];self.runOnStartup=function(p){if("function"!==typeof p)throw Error("runOnStartup called without a function");B.push(p)};const r=new Set(["cordova","playable-ad","instant-games"]);function y(p){return r.has(p)}window.RuntimeInterface=class p{constructor(c){this._useWorker=c.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=c.scriptFolder;this._workerScriptBlobURLs={};this._loadingElem=this._localRuntime=this._worker=null;this._domHandlers=
[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=c.exportType;!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this._useWorker=!1);y(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this._useWorker=!1);this._localFileStrings=this._localFileBlobs=
null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",e=>this._OnCordovaFetchLocalFile(e));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",e=>this._OnCreateJobWorker(e));"cordova"===this._exportType?
document.addEventListener("deviceready",()=>this._Init(c)):this._Init(c)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return d&&
"cordova"===this._exportType}IsiOSWebView(){return d&&y(this._exportType)||navigator.standalone}async _Init(c){"preview"===this._exportType&&(this._loadingElem=document.createElement("div"),this._loadingElem.className="previewLoadingMessage",this._loadingElem.textContent=c.previewLoadingMessage,document.body.appendChild(this._loadingElem));if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let a=0,b=c.engineScripts.length;a<
b;++a){var e=c.engineScripts[a].toLowerCase();this._localFileStrings.hasOwnProperty(e)?c.engineScripts[a]={isStringSrc:!0,str:this._localFileStrings[e]}:this._localFileBlobs.hasOwnProperty(e)&&(c.engineScripts[a]=URL.createObjectURL(this._localFileBlobs[e]))}}c.baseUrl?this._baseUrl=c.baseUrl:(e=location.origin,this._baseUrl=("null"===e?"file:///":e)+location.pathname,e=this._baseUrl.lastIndexOf("/"),-1!==e&&(this._baseUrl=this._baseUrl.substr(0,e+1)));if(c.workerScripts)for(const [a,b]of Object.entries(c.workerScripts))this._workerScriptBlobURLs[a]=
URL.createObjectURL(b);e=new MessageChannel;this._messageChannelPort=e.port1;this._messageChannelPort.onmessage=a=>this._OnMessageFromRuntime(a.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(a=>this._OnMessageFromDebugger(a));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();
this._useWorker?await this._InitWorker(c,e.port2):await this._InitDOM(c,e.port2)}_GetWorkerURL(c){return this._workerScriptBlobURLs.hasOwnProperty(c)?this._workerScriptBlobURLs[c]:c.endsWith("/workermain.js")&&this._workerScriptBlobURLs.hasOwnProperty("workermain.js")?this._workerScriptBlobURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(c.toLowerCase())?URL.createObjectURL(this._localFileBlobs[c.toLowerCase()]):c}async CreateWorker(c,e,a){if(c.startsWith("blob:"))return new Worker(c,
a);if(this.IsiOSCordova()&&"file:"===location.protocol)return c=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+c),c=new Blob([c],{type:"application/javascript"}),new Worker(URL.createObjectURL(c),a);c=new URL(c,e);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),a)}return new Worker(c,a)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,
1)}MaybeForceBodySize(){if(this.IsiOSWebView()){const c=document.documentElement.style,e=document.body.style,a=window.innerWidth<window.innerHeight,b=a?window.screen.width:window.screen.height;e.height=c.height=(a?window.screen.height:window.screen.width)+"px";e.width=c.width=b+"px"}}_GetCommonRuntimeOptions(c){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:p.IsDocumentFullscreen(),
projectData:c.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:c.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:m,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),
isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(c,e){var a=this._GetWorkerURL(c.workerMainUrl);this._worker=await this.CreateWorker(a,this._baseUrl,{name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display="none";a=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(c),{type:"init-runtime",
isInWorker:!0,messagePort:e,canvas:a,workerDependencyScripts:c.workerDependencyScripts||[],engineScripts:c.engineScripts,projectScripts:window.cr_allProjectScripts,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[e,a,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=t.map(b=>new b(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(b,f)=>this._runtimeDomHandler._InvokeFunctionFromJS(b,f);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime",
"go-to-last-error-script"))}async _InitDOM(c,e){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=t.map(b=>new b(this));this._FindRuntimeDOMHandler();const a=c.engineScripts.map(b=>"string"===typeof b?(new URL(b,this._baseUrl)).toString():b);Array.isArray(c.workerDependencyScripts)&&a.unshift(...c.workerDependencyScripts);await Promise.all(a.map(b=>g(b)));if(c.projectScripts&&0<c.projectScripts.length){const b=
self.C3_ProjectScriptsStatus;try{if(await Promise.all(c.projectScripts.map(f=>g(f[1]))),Object.values(b).some(f=>!f)){self.setTimeout(()=>this._ReportProjectScriptError(b),100);return}}catch(f){console.error("[Preview] Error loading project scripts: ",f);self.setTimeout(()=>this._ReportProjectScriptError(b),100);return}}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this._GetCommonRuntimeOptions(c),{isInWorker:!1,messagePort:e,canvas:this._canvas,runOnStartupFunctions:B}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this._localRuntime,c))}_ReportProjectScriptError(c){this._RemoveLoadingMessage();c=`Failed to load project script '${Object.entries(c).filter(e=>!e[1]).map(e=>e[0])[0]}'. Check all your JavaScript code has valid syntax.`;
console.error("[Preview] "+c);alert(c)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){this._loadingElem&&(this._loadingElem.parentElement.removeChild(this._loadingElem),this._loadingElem=null)}async _OnCreateJobWorker(c){c=await this._jobScheduler._CreateJobWorker();return{outputPort:c,transferables:[c]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(c,e,a,b,f){this._messageChannelPort.postMessage({type:"event",
component:c,handler:e,dispatchOpts:b||null,data:a,responseId:null},f)}PostToRuntimeComponentAsync(c,e,a,b,f){const h=A++,l=new Promise((q,C)=>{x.set(h,{resolve:q,reject:C})});this._messageChannelPort.postMessage({type:"event",component:c,handler:e,dispatchOpts:b||null,data:a,responseId:h},f);return l}["_OnMessageFromRuntime"](c){const e=c.type;if("event"===e)return this._OnEventFromRuntime(c);if("result"===e)this._OnResultFromRuntime(c);else if("runtime-ready"===e)this._OnRuntimeReady();else if("alert-error"===
e)this._RemoveLoadingMessage(),alert(c.message);else if("creating-runtime"===e)this._OnBeforeCreateRuntime();else throw Error(`unknown message '${e}'`);}_OnEventFromRuntime(c){const e=c.component,a=c.handler,b=c.data,f=c.responseId;if(c=w.get(e))if(c=c.get(a)){var h=null;try{h=c(b)}catch(l){console.error(`Exception in '${e}' handler '${a}':`,l);null!==f&&this._PostResultToRuntime(f,!1,""+l);return}if(null===f)return h;h&&h.then?h.then(l=>this._PostResultToRuntime(f,!0,l)).catch(l=>{console.error(`Rejection from '${e}' handler '${a}':`,
l);this._PostResultToRuntime(f,!1,""+l)}):this._PostResultToRuntime(f,!0,h)}else console.warn(`[DOM] No handler '${a}' for component '${e}'`);else console.warn(`[DOM] No event handlers for component '${e}'`)}_PostResultToRuntime(c,e,a){let b;a&&a.transferables&&(b=a.transferables);this._messageChannelPort.postMessage({type:"result",responseId:c,isOk:e,result:a},b)}_OnResultFromRuntime(c){const e=c.responseId,a=c.isOk;c=c.result;const b=x.get(e);a?b.resolve(c):b.reject(c);x.delete(e)}AddRuntimeComponentMessageHandler(c,
e,a){let b=w.get(c);b||(b=new Map,w.set(c,b));if(b.has(e))throw Error(`[DOM] Component '${c}' already has handler '${e}'`);b.set(e,a)}static AddDOMHandlerClass(c){if(t.includes(c))throw Error("DOM handler already added");t.push(c)}_FindRuntimeDOMHandler(){for(const c of this._domHandlers)if("runtime"===c.GetComponentID()){this._runtimeDomHandler=c;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(c){this.PostToRuntimeComponent("debugger","message",c)}_OnRuntimeReady(){for(const c of this._domHandlers)c.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(c){this._rafCallbacks.push(c);this._RequestAnimationFrame()}_RemoveRAFCallback(c){c=this._rafCallbacks.indexOf(c);if(-1===c)throw Error("invalid callback");this._rafCallbacks.splice(c,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&
(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const c of this._rafCallbacks)c();this._RequestAnimationFrame()}TryPlayMedia(c){this._runtimeDomHandler.TryPlayMedia(c)}RemovePendingPlay(c){this._runtimeDomHandler.RemovePendingPlay(c)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(c){this._runtimeDomHandler.SetSilent(c)}IsAudioFormatSupported(c){return!!m[c]}async _WasmDecodeWebMOpus(c){c=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}IsAbsoluteURL(c){return/^(?:[a-z]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}IsRelativeURL(c){return!this.IsAbsoluteURL(c)}async _OnCordovaFetchLocalFile(c){const e=c.filename;switch(c.as){case "text":return await this.CordovaFetchLocalFileAsText(e);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(e);default:throw Error("unsupported type");}}_GetPermissionAPI(){const c=
window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof c)throw Error("Permission API is not loaded");return c}_MapPermissionID(c,e){c=c[e];if("string"!==typeof c)throw Error("Invalid permission name");return c}_HasPermission(c){const e=this._GetPermissionAPI();return new Promise((a,b)=>e.checkPermission(this._MapPermissionID(e,c),f=>a(!!f.hasPermission),b))}_RequestPermission(c){const e=this._GetPermissionAPI();return new Promise((a,b)=>e.requestPermission(this._MapPermissionID(e,
c),f=>a(!!f.hasPermission),b))}async RequestPermissions(c){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const e of c)if(!await this._HasPermission(e)&&!1===await this._RequestPermission(e))return!1;return!0}async RequirePermissions(...c){if(!1===await this.RequestPermissions(c))throw Error("Permission not granted");}CordovaFetchLocalFile(c){const e=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((a,b)=>{window.resolveLocalFileSystemURL(e,
f=>{f.file(a,b)},b)})}async CordovaFetchLocalFileAsText(c){c=await this.CordovaFetchLocalFile(c);return await n(c)}_CordovaMaybeStartNextArrayBufferRead(){if(v.length&&!(8<=u)){u++;var c=v.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(c.filename,c.successCallback,c.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(c){return new Promise((e,a)=>{v.push({filename:c,successCallback:b=>{u--;this._CordovaMaybeStartNextArrayBufferRead();e(b)},errorCallback:b=>{u--;this._CordovaMaybeStartNextArrayBufferRead();
a(b)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(c,e,a){try{const b=await this.CordovaFetchLocalFile(c),f=await z(b);e(f)}catch(b){a(b)}}async _ConvertDataUrisToBlobs(){const c=[];for(const [e,a]of Object.entries(this._localFileBlobs))c.push(this._ConvertDataUriToBlobs(e,a));await Promise.all(c)}async _ConvertDataUriToBlobs(c,e){if("object"===typeof e)this._localFileBlobs[c]=new Blob([e.str],{type:e.type}),this._localFileStrings[c]=e.str;else{let a=
await this._FetchDataUri(e);a||(a=this._DataURIToBinaryBlobSync(e));this._localFileBlobs[c]=a}}async _FetchDataUri(c){try{return await (await fetch(c)).blob()}catch(e){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",e),null}}_DataURIToBinaryBlobSync(c){c=this._ParseDataURI(c);return this._BinaryStringToBlob(c.data,c.mime_type)}_ParseDataURI(c){var e=
c.indexOf(",");if(0>e)throw new URIError("expected comma in data: uri");var a=c.substring(5,e);c=c.substring(e+1);e=a.split(";");a=e[0]||"";const b=e[2];c="base64"===e[1]||"base64"===b?atob(c):decodeURIComponent(c);return{mime_type:a,data:c}}_BinaryStringToBlob(c,e){var a=c.length;let b=a>>2,f=new Uint8Array(a),h=new Uint32Array(f.buffer,0,b),l,q;for(q=l=0;l<b;++l)h[l]=c.charCodeAt(q++)|c.charCodeAt(q++)<<8|c.charCodeAt(q++)<<16|c.charCodeAt(q++)<<24;for(a&=3;a--;)f[q]=c.charCodeAt(q),++q;return new Blob([f],
{type:e})}}}"use strict";
{const d=self.RuntimeInterface;function g(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const k=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),m={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},n={dispatchUserScriptEvent:!0},z={dispatchRuntimeEvent:!0};function v(a){return new Promise((b,f)=>{const h=document.createElement("link");h.onload=()=>b(h);h.onerror=
l=>f(l);h.rel="stylesheet";h.href=a;document.head.appendChild(h)})}function u(a){return new Promise((b,f)=>{const h=new Image;h.onload=()=>b(h);h.onerror=l=>f(l);h.src=a})}async function t(a){a=URL.createObjectURL(a);try{return await u(a)}finally{URL.revokeObjectURL(a)}}function w(a){return new Promise((b,f)=>{let h=new FileReader;h.onload=l=>b(l.target.result);h.onerror=l=>f(l);h.readAsText(a)})}async function x(a,b,f){if(!/firefox/i.test(navigator.userAgent))return await t(a);var h=await w(a);h=
(new DOMParser).parseFromString(h,"image/svg+xml");const l=h.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const q=l.getAttribute("width"),C=l.getAttribute("height");if(!q.includes("%")&&!C.includes("%"))return await t(a)}l.setAttribute("width",b+"px");l.setAttribute("height",f+"px");h=(new XMLSerializer).serializeToString(h);a=new Blob([h],{type:"image/svg+xml"});return await t(a)}function A(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);
return!1}const B=new Set(["canvas","body","html"]);function r(a){const b=a.target.tagName.toLowerCase();B.has(b)&&a.preventDefault()}function y(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}self.C3_GetSvgImageSize=async function(a){a=await t(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();document.body.removeChild(a);return[b.width,b.height]}};
self.C3_RasterSvgImageBlob=async function(a,b,f,h,l){a=await x(a,b,f);const q=document.createElement("canvas");q.width=h;q.height=l;q.getContext("2d").drawImage(a,0,0,b,f);return q};let p=!1;document.addEventListener("pause",()=>p=!0);document.addEventListener("resume",()=>p=!1);function c(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}}function e(){const a=document.activeElement;if(!a)return!1;const b=a.tagName.toLowerCase(),f=new Set("email number password search tel text url".split(" "));
return"textarea"===b?!0:"input"===b?f.has(a.type.toLowerCase()||"text"):A(a)}d.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;a.AddRuntimeComponentMessageHandler("canvas","update-size",h=>this._OnUpdateCanvasSize(h));
a.AddRuntimeComponentMessageHandler("runtime","invoke-download",h=>this._OnInvokeDownload(h));a.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",h=>this._OnRasterSvgImage(h));a.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",h=>this._OnGetSvgImageSize(h));a.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",h=>this._OnSetTargetOrientation(h));a.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());a.AddRuntimeComponentMessageHandler("runtime",
"post-to-debugger",h=>this._OnPostToDebugger(h));a.AddRuntimeComponentMessageHandler("runtime","go-to-script",h=>this._OnPostToDebugger(h));a.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());a.AddRuntimeComponentMessageHandler("runtime","debug-highlight",h=>this._OnDebugHighlight(h));a.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());a.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",
()=>this._AttachDeviceMotionEvent());a.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",h=>this._OnAddStylesheet(h));a.AddRuntimeComponentMessageHandler("runtime","alert",h=>this._OnAlert(h));a.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",h=>{const l=h.target,q=l.tagName.toLowerCase();b.has(q)||A(l)||h.preventDefault()});const f=a.GetCanvas();window.addEventListener("selectstart",
r);window.addEventListener("gesturehold",r);f.addEventListener("selectstart",r);f.addEventListener("gesturehold",r);window.addEventListener("touchstart",r,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",r,{passive:!1}),f.addEventListener("pointerdown",r)):f.addEventListener("touchstart",r);this._mousePointerLastButtons=0;window.addEventListener("mousedown",h=>{1===h.button&&h.preventDefault()});window.addEventListener("mousewheel",y,{passive:!1});window.addEventListener("wheel",
y,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());a.IsiOSWebView()&&window.addEventListener("focusout",()=>{e()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",
()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!p)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:c()});this._mousePointerLastButtons=0});window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",
()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",b=>this._OnFullscreenError(b));window.addEventListener("webkitfullscreenerror",b=>this._OnFullscreenError(b));window.addEventListener("mozfullscreenerror",b=>this._OnFullscreenError(b));window.addEventListener("keydown",b=>this._OnKeyEvent("keydown",b));window.addEventListener("keyup",b=>this._OnKeyEvent("keyup",b));window.addEventListener("dblclick",b=>this._OnMouseEvent("dblclick",b,m));window.addEventListener("wheel",b=>
this._OnMouseWheelEvent("wheel",b));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{this._HandlePointerDownFocus(b);this._OnPointerEvent("pointerdown",b)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",b=>this._OnPointerRawUpdate(b))):
window.addEventListener("pointermove",b=>this._OnPointerEvent("pointermove",b)),window.addEventListener("pointerup",b=>this._OnPointerEvent("pointerup",b)),window.addEventListener("pointercancel",b=>this._OnPointerEvent("pointercancel",b))):(window.addEventListener("mousedown",b=>{this._HandlePointerDownFocus(b);this._OnMouseEventAsPointer("pointerdown",b)}),window.addEventListener("mousemove",b=>this._OnMouseEventAsPointer("pointermove",b)),window.addEventListener("mouseup",b=>this._OnMouseEventAsPointer("pointerup",
b)),window.addEventListener("touchstart",b=>{this._HandlePointerDownFocus(b);this._OnTouchEvent("pointerdown",b)}),window.addEventListener("touchmove",b=>this._OnTouchEvent("pointermove",b)),window.addEventListener("touchend",b=>this._OnTouchEvent("pointerup",b)),window.addEventListener("touchcancel",b=>this._OnTouchEvent("pointercancel",b)));const a=()=>this._PlayPendingMedia();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);
window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}_PostRuntimeEvent(a,b){this.PostToRuntime(a,b||null,z)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const a=this._GetWindowInnerWidth(),b=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:a,innerHeight:b,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&
(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(a,b,0))}_ScheduleSimulatedResize(a,b,f){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(a,b,f),48)}_OnSimulatedResize(a,b,f){const h=this._GetWindowInnerWidth(),l=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;h!=a||l!=b?this._PostRuntimeEvent("window-resize",{innerWidth:h,innerHeight:l,
devicePixelRatio:window.devicePixelRatio}):10>f&&this._ScheduleSimulatedResize(h,l,f+1)}_OnSetTargetOrientation(a){this._targetOrientation=a.targetOrientation}_TrySetTargetOrientation(){const a=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct 3] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?
b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct 3] Failed to lock orientation")}catch(b){console.warn("[Construct 3] Failed to lock orientation: ",b)}}_OnFullscreenChange(){const a=d.IsDocumentFullscreen();a&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:a,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(a){console.warn("[Construct 3] Fullscreen request failed: ",
a);this.PostToRuntime("fullscreenerror",{isFullscreen:d.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(a){a?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:a})}_OnKeyEvent(a,b){"Backspace"===b.key&&r(b);const f=k.get(b.code)||b.code;this._PostToRuntimeMaybeSync(a,{code:f,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,
metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},m)}_OnMouseWheelEvent(a,b){this.PostToRuntime(a,{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},m)}_OnMouseEvent(a,b,f){g(b)||this._PostToRuntimeMaybeSync(a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,timeStamp:b.timeStamp},f)}_OnMouseEventAsPointer(a,b){if(!g(b)){var f=this._mousePointerLastButtons;
"pointerdown"===a&&0!==f?a="pointermove":"pointerup"===a&&0!==b.buttons&&(a="pointermove");this._PostToRuntimeMaybeSync(a,{pointerId:1,pointerType:"mouse",button:b.button,buttons:b.buttons,lastButtons:f,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:b.timeStamp},m);this._mousePointerLastButtons=b.buttons;this._OnMouseEvent(b.type,b,n)}}_OnPointerEvent(a,b){this._pointerRawUpdateRateLimiter&&"pointermove"!==
a&&this._pointerRawUpdateRateLimiter.Reset();var f=0;"mouse"===b.pointerType&&(f=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:f,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},m);"mouse"===b.pointerType&&
(f="mousemove","pointerdown"===a?f="mousedown":"pointerup"===a&&(f="pointerup"),this._OnMouseEvent(f,b,n),this._mousePointerLastButtons=b.buttons)}_OnPointerRawUpdate(a){this._lastPointerRawUpdateEvent=a;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(a,b){for(let f=0,h=b.changedTouches.length;f<h;++f){const l=b.changedTouches[f];this._PostToRuntimeMaybeSync(a,
{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:b.timeStamp},m)}}_HandlePointerDownFocus(a){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(a.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",a=>this._OnDeviceOrientation(a)),window.addEventListener("deviceorientationabsolute",a=>this._OnDeviceOrientationAbsolute(a)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=
!0,window.addEventListener("devicemotion",a=>this._OnDeviceMotion(a)))}_OnDeviceOrientation(a){this.PostToRuntime("deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},m)}_OnDeviceOrientationAbsolute(a){this.PostToRuntime("deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},m)}_OnDeviceMotion(a){let b=
null;var f=a.acceleration;f&&(b={x:f.x||0,y:f.y||0,z:f.z||0});f=null;var h=a.accelerationIncludingGravity;h&&(f={x:h.x||0,y:h.y||0,z:h.z||0});h=null;const l=a.rotationRate;l&&(h={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});this.PostToRuntime("devicemotion",{acceleration:b,accelerationIncludingGravity:f,rotationRate:h,interval:a.interval,timeStamp:a.timeStamp},m)}_OnUpdateCanvasSize(a){const b=this.GetRuntimeInterface(),f=b.GetCanvas();f.style.width=a.styleWidth+"px";f.style.height=a.styleHeight+
"px";f.style.marginLeft=a.marginLeft+"px";f.style.marginTop=a.marginTop+"px";b.MaybeForceBodySize();this._isFirstSizeUpdate&&(f.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(a){const b=a.url;a=a.filename;const f=document.createElement("a"),h=document.body;f.textContent=a;f.href=b;f.download=a;h.appendChild(f);f.click();h.removeChild(f)}async _OnRasterSvgImage(a){var b=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);
b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async _OnGetSvgImageSize(a){return await self.C3_GetSvgImageSize(a.blob)}async _OnAddStylesheet(a){await v(a.url)}_PlayPendingMedia(){var a=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const b of a)(a=b.play())&&a.catch(f=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}TryPlayMedia(a){if("function"!==typeof a.play)throw Error("missing play function");
this._mediaRemovedPendingPlay.delete(a);let b;try{b=a.play()}catch(f){this._mediaPendingPlay.add(a);return}b&&b.catch(f=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}RemovePendingPlay(a){this._mediaPendingPlay.delete(a);this._mediaRemovedPendingPlay.add(a)}SetSilent(a){this._isSilent=!!a}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(a){if(a.show){this._debugHighlightElem||(this._debugHighlightElem=
document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var b=this._debugHighlightElem;b.style.display="";b.style.left=a.left-1+"px";b.style.top=a.top-1+"px";b.style.width=a.width+2+"px";b.style.height=a.height+2+"px";b.textContent=a.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(a){window.c3_postToMessagePort&&
(a.from="runtime",window.c3_postToMessagePort(a))}_InvokeFunctionFromJS(a,b){return this.PostToRuntimeAsync("js-invoke-function",{name:a,params:b})}_OnAlert(a){alert(a.message)}})}"use strict";
self.JobSchedulerDOM=class{constructor(d){this._runtimeInterface=d;this._baseUrl=d.GetBaseURL();"preview"===d.GetExportType()?this._baseUrl+="c3/workers/":this._baseUrl+=d.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var d=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(d,this._baseUrl,{name:"DispatchWorker"});d=new MessageChannel;this._inputPort=d.port1;this._dispatchWorker.postMessage({type:"_init","in-port":d.port2},[d.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const d=this._jobWorkers.length;var g=this._runtimeInterface._GetWorkerURL("jobworker.js");g=await this._runtimeInterface.CreateWorker(g,this._baseUrl,{name:"JobWorker"+d});const k=new MessageChannel,m=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:k.port1},[k.port1]);g.postMessage({type:"init",number:d,"dispatch-port":k.port2,"output-port":m.port2},[k.port2,m.port2]);this._jobWorkers.push(g);return m.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
{function d(g){g.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(g){super(g,"button")}CreateElement(g,k){const m=document.createElement("input");var n=m;k.isCheckbox?(m.type="checkbox",n=document.createElement("label"),n.appendChild(m),n.appendChild(document.createTextNode("")),n.style.fontFamily="sans-serif",n.style.userSelect="none",n.style.webkitUserSelect="none",n.style.display="inline-block",n.style.color="black"):m.type="button";n.style.position=
"absolute";n.addEventListener("touchstart",d);n.addEventListener("touchmove",d);n.addEventListener("touchend",d);n.addEventListener("mousedown",d);n.addEventListener("mouseup",d);n.addEventListener("keydown",d);n.addEventListener("keyup",d);m.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",g,{isChecked:m.checked}));k.id&&(m.id=k.id);this.UpdateState(n,k);return n}_GetInputElem(g){return"input"===g.tagName.toLowerCase()?g:g.firstChild}_GetFocusElement(g){return this._GetInputElem(g)}UpdateState(g,
k){const m=this._GetInputElem(g);m.checked=k.isChecked;m.disabled=!k.isEnabled;g.title=k.title;g===m?m.value=k.text:g.lastChild.textContent=k.text}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"touch");this.AddRuntimeMessageHandler("request-permission",g=>this._OnRequestPermission(g))}async _OnRequestPermission(d){d=d.type;let g=!0;0===d?g=await this._RequestOrientationPermission():1===d&&(g=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:d,result:g})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"mouse");this.AddRuntimeMessageHandler("cursor",g=>this._OnChangeCursorStyle(g))}_OnChangeCursorStyle(d){document.documentElement.style.cursor=d}});